#!/usr/bin/env ruby
require 'erb'
require 'open3'

def parse_erb(file)
  Open3.popen3('ruby -Ku -c') do |stdin, stdout, stderr|
    stdin.puts(ERB.new(File.read(file), nil, '-').src)
    stdin.close
    if error = ((stderr.readline rescue false))
      raise error[1..-1].sub(/^[^:]*:\d+: /, '')
    end
    stdout.close rescue false
    stderr.close rescue false
  end
end

exit_code = 0
Dir.glob("**/*.erb").each do |file|
  begin
    puts "Checking ERB syntax for #{file}"
    parse_erb(file)
  rescue StandardError => e
    puts "\e[31mFailed to parse #{file} with error:\n#{e.message}\e[0m"
    exit_code = 1
  end
end
exit exit_code
